. ~/.shell/bash
. ~/.shell/path
. ~/.shell/functions
. ~/.shell/aliases
. ~/.shell/colors
. ~/.shell/exports
. ~/.shell/vault
. ~/.shell/tmux
. ~/.shell/docker
. ~/.shell/kubernetes

. ~/.rvm/scripts/rvm

which brew > /dev/null 2>&1
[[ $? -eq 0 ]] && {
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
    . ~/.shell/complete
  fi
}
. ~/.shell/bin/bash-preexec.sh
. ~/.shell/preexeccmd

eval "$(direnv hook bash)"
gopath
