""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                                                              "
" VIM Configuration File                                                       "
"                                                                              "
" Author:  Cody Buell <cody@codybuell.com>                                     "
"                                                                              "
" Mappings:                                                                    "
"                                                                              "
"  Leader --------->  ␣ (spacebar)                                             "
"  Local Leader --->  \                                                        "
"                                                                              "
"  normal mode                                                                 "
"  -----------                                                                 "
"                                                                              "
"  -   vim vinegar          ␣t  cmnd-t               <c-h> focus left split    "
"  ␣-  nerdtree             ␣T  cmnd-t mru           <c-j> focus down split    "
"  ␣=  math ("[letter]p)    ␣y  cmnd-t buffers       <c-k> focus up split      "
"  ␣`  toggle nu & list     ␣Y  cmnd-t tags          <c-l> focus right split   "
"  ␣1  toggle wrapping      ␣j  cmnd-t jumplist      <tab> toggle fold         "
"  ␣2  toggle comments      ␣h  cmnd-t vim help      ␣w    write buffer        "
"  ␣3  toggle syntax hi     ␣n  cmnd-t notes         ␣q    close buffer        "
"  ␣4  delete view file     ␣m  cmnd-t lv models     ␣␣    toggle buffer       "
"  ␣5                       ␣v  cmnd-t lv views      ␣                         "
"  ␣6  hitest.vim           ␣c  cmnd-t lv contrlrs   ␣                         "
"  ␣7  insert color ref     ␣st cmnd-t lv styles     ␣                         "
"  ␣8  show hl groups       ␣sc cmnd-t lv scripts    ␣                         "
"  ␣9  toggle errorlist     ␣                        ␣                         "
"  ␣0  toggle tagbar        ␣                        ␣                         "
"  ␣                        ␣                        ␣                         "
"  ␣                        ␣ev edit vimrc           ␣                         "
"  ␣                        ␣es edit snippets        ␣r    gen random chars    "
"  ␣                        ␣eu edit ultisnips       ␣z    zoom on split       "
"  ␣                        ␣er edit laravel routes  ,/    remove search hi    "
"  ␣                        ␣ec edit laravel config  \c    fix syntax hi       "
"  ␣sp syncscroll vsplit    ␣ed edit laravel db      \u    underline text      "
"                                                                              "
"  insert mode                                                                 "
"  -----------                                                                 "
"                                                                              "
"  \u  underline text                                                          "
"  \c  fix coloring                                                            "
"                                                                              "
"  visual mode                                                                 "
"  -----------                                                                 "
"                                                                              "
"  ␣sl sort by length       ␣=  math "[s|a|n|x]p                               "
"  ␣so sort selection                                                          "
"  v   expand selection                                                        "
"  C-v shrink selection                                                        "
"                                                                              "
"  command mode                                                                "
"  ------------                                                                "
"                                                                              "
"                                                                              "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"//////////////////////////////////////"
"//                                  //"
"//  Pathogen / Third Party Plugins  //"
"//                                  //"
"//////////////////////////////////////"

" load pathogen from bundle directory rather than autoload
runtime bundle/vim-pathogen/autoload/pathogen.vim

" define pathogen runtime roots
execute pathogen#infect('bundle/{}')

" always execute loading of help files
Helptags

"////////////////////////"
"//                    //"
"//  Override Leaders  //"
"//                    //"
"////////////////////////"

let mapleader="\<Space>"
let maplocalleader="\\"

"////////////////////////"
"//                    //"
"//  General Settings  //"
"//                    //"
"////////////////////////"

" configure file type detection and allow ft plugins
filetype plugin indent on

" turn on syntax highlighting
syntax on

" set config options
set nocompatible                                   " disable compatability mode
set incsearch                                      " search as chars are entered
set hlsearch                                       " highlight search results
set history=100                                    " keep 100 lines of history
set ruler                                          " show the  position
set sts=2                                          " sets the soft tab stop
set ts=2                                           " tab stop to 4 spaces
set sw=2                                           " shift width, auto ind / shifting spaces
set shiftround                                     " always indent by multiple of shiftwidth
set ai                                             " auto indenting
set et                                             " expand tabs to spaces
set scrolloff=4                                    " scroll before end of page
set enc=utf-8                                      " default to utf-8 encoding
set visualbell                                     " stop beeps and alerts
set noerrorbells                                   " stop beeps and alerts
set t_vb=                                          " stop beeps and alerts
set nu                                             " turn on line numbers
set rnu                                            " turn on relative line numbers
set linespace=15                                   " increase line height (gvim)
set cursorline                                     " highight line cursor is on
set wildmenu                                       " improved file open menu
set lazyredraw                                     " no redraw during macros etc
set list                                           " show special characters
set lcs=eol:¬,tab:>-,trail:.,extends:»,precedes:«  " special character labels
set backspace=2                                    " make bkspace work on line br & auto indents
set noshowmode                                     " dont show modes, statusline does it
set complete=.,w,b,u                               " auto complete from current file, window, buffers
set ignorecase                                     " case insensitive searching
set smartcase                                      " except when there is an uc char in search
"set nofoldenable                                  " open files without folding
set foldmethod=syntax                              " enable folding by syntax
set foldlevel=1                                    " fold second level and greater
set foldcolumn=2                                   " show the fold column
set laststatus=2                                   " enable statusline
set shortmess+=I                                   " no intro text on plain vi start
set highlight+=N:DiffText                          " make current line number stand out a little
set selection=exclusive                            " include the last character when dbl click selecting
set splitbelow                                     " open new splits on the bottom
"set nowrap                                        " disable wrapping by default

" mouse configs
nnoremap <silent> <2-LeftMouse> :<C-U>call functions#DblClickOverride()<CR>

" enable folding by file type
let g:javaScript_fold=1                            " javascript
let g:perl_fold=1                                  " perl
let g:php_folding=1                                " php
let g:r_syntax_folding=1                           " r
let g:ruby_fold=1                                  " ruby
let g:sh_fold_enabled=1                            " sh
let g:vimsyn_folding='af'                          " vim script
let g:xml_syntax_folding=1                         " xml

" custom line break symbol
if has('linebreak')
  let &showbreak='»» '
  set breakindent
  if exists('&breakindentopt')
    set breakindentopt=shift:0
  endif
endif

" meta file handling
if exists('$SUDO_USER')
  " don't create root owned files
  set noswapfile
  set nobackup
  set nowritebackup
  set noundofile
  set viminfo=
else
  " else keep everything in vim/tmp
  set backupdir=~/.vim/tmp/backup
  set directory=~/.vim/tmp/swap
  set viminfo+=n~/.vim/tmp/viminfo
  set viewdir=~/.vim/tmp/view
  set undodir=~/.vim/tmp/undo
  " set undofile
endif

" highlight when slopping over 80 columns
call matchadd('ColorColumn', '\%81v', 100)

"///////////////////////"
"//                   //"
"//  Global Settings  //"
"//                   //"
"///////////////////////"

" set config options
setglobal rnu                                      " turn on relative line numbers

"//////////////////////////////////////"
"//                                  //"
"//  Order Sensitive Configurations  //"
"//                                  //"
"//////////////////////////////////////"

" let vim vinegar do its things
let g:NERDTreeHijackNetrw = 0

" easymotion don't use space space, want that for toggling buffers
map <localleader><localleader> <Plug>(easymotion-prefix)

" use enter to identify completion selection (C-y is the default)
let g:SuperTabCrMapping=1
