""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                                                              "
" VIM Configuration File                                                       "
"                                                                              "
" Author:  Cody Buell <cody@codybuell.com>                                     "
"                                                                              "
" Mappings:                                                                    "
"                                                                              "
"  normal mode                                                                 "
"  -----------                                                                 "
"                                                                              "
"  -   vim vinegar          \t  command-t            <c-h> focus left split    "
"  \-  nerdtree             \T  command-t mru        <c-j> focus down split    "
"  \=  math ("[letter]p)    \y  command-t buffers    <c-k> focus up split      "
"  \`  toggle nu & list     \Y  command-t tags       <c-l> focus right split   "
"  \1  toggle wrapping      \j  command-t jumplist   \                         "
"  \2                       \z  zoom on split        \                         "
"  \3  inser color ref      \q  close buffer         \                         "
"  \4                       \w  write buffer         \                         "
"  \5                       \c  fix coloring         \                         "
"  \6                       \u  underline text       \                         "
"  \7                       \                        \                         "
"  \8  show hl groups       \                        \                         "
"  \9  toggle errorlist     \                        \                         "
"  \0  toggle tagbar        \                        \                         "
"                                                                              "
"  insert mode                                                                 "
"  -----------                                                                 "
"                                                                              "
"  \u  underline text                                                          "
"  \c  fix coloring                                                            "
"                                                                              "
"  visual mode                                                                 "
"  -----------                                                                 "
"                                                                              "
"                                                                              "
"  command mode                                                                "
"  ------------                                                                "
"                                                                              "
"                                                                              "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"//////////////////////////////////////"
"//                                  //"
"//  Pathogen / Third Party Plugins  //"
"//                                  //"
"//////////////////////////////////////"

" load pathogen from bundle directory rather than autoload
runtime bundle/vim-pathogen/autoload/pathogen.vim

" define pathogen runtime roots
execute pathogen#infect('bundle/{}')

"////////////////////////"
"//                    //"
"//  General Settings  //"
"//                    //"
"////////////////////////"

" configure file type detection and allow ft plugins
filetype plugin indent on

" turn on syntax highlighting
syntax on

" set config options
set nocompatible                                   " disable compatability mode
set incsearch                                      " search as chars are entered
set hlsearch                                       " highlight search results
set history=100                                    " keep 100 lines of history
set ruler                                          " show the cursor position
set sts=2                                          " sets the soft tab stop
set ts=2                                           " tab stop to 4 spaces
set sw=2                                           " shift width, auto ind / shifting spaces
set shiftround                                     " always indent by multiple of shiftwidth
set ai                                             " auto indenting
set et                                             " expand tabs to spaces
set scrolloff=4                                    " scroll before end of page
set enc=utf-8                                      " default to utf-8 encoding
set visualbell                                     " stop beeps and alerts
set noerrorbells                                   " stop beeps and alerts
set t_vb=                                          " stop beeps and alerts
set nu                                             " turn on line numbers
set rnu                                            " turn on relative line numbers
set linespace=15                                   " increase line height (gvim)
set cursorline                                     " highight line cursor is on
set wildmenu                                       " improved file open menu
set lazyredraw                                     " no redraw during macros etc
set list                                           " show special characters
set lcs=eol:¬,tab:>-,trail:.,extends:»,precedes:«  " special character labels
set backspace=2                                    " make bkspace work on line br & auto indents
set noshowmode                                     " dont show modes, statusline does it
set complete=.,w,b,u                               " auto complete from current file, window, buffers
set ignorecase                                     " case insensitive searching
set smartcase                                      " except when there is an uc char in search
set nofoldenable                                   " open files without folding
set foldlevel=1                                    " fold second level and greater
set foldcolumn=2                                   " show the fold column
set laststatus=2                                   " enable statusline
set shortmess+=I                                   " no intro text on plain vi start
set highlight+=N:DiffText                          " make current line number stand out a little

" custom line break symbol
if has('linebreak')
  let &showbreak='⤷ '
endif

" meta file handling
if exists('$SUDO_USER')
  " don't create root owned files
  set noswapfile
  set nobackup
  set nowritebackup
  set noundofile
  set viminfo=
else
  " else keep everything in vim/tmp
  set backupdir=~/.vim/tmp/backup
  set directory=~/.vim/tmp/swap
  set viminfo+=n~/.vim/tmp/viminfo
  set viewdir=~/.vim/tmp/view
  set undodir=~/.vim/tmp/undo
  set undofile
endif

" highlight when slopping over 80 columns
call matchadd('ColorColumn', '\%81v', 100)

"///////////////////////"
"//                   //"
"//  Global Settings  //"
"//                   //"
"///////////////////////"

" set config options
setglobal rnu                                      " turn on relative line numbers

"//////////////////////////////////////"
"//                                  //"
"//  Order Sensitive Configurations  //"
"//                                  //"
"//////////////////////////////////////"

" let vim vinegar do its things
let g:NERDTreeHijackNetrw = 0
